### ISSUE TITLE
(Windows) Zadig Dongle instructions

### ISSUE THREAD

**Issue by Hoverbear** [ferrous-systems/embedded-trainings-2020#85]
While reading the Windows instructions for setup I noticed the details only cover the DK.

`/installation.html#windows-only-zadig-jlink-driver`
![image](https://user-images.githubusercontent.com/130903/88118253-080cfa80-cb72-11ea-8a38-9efcd1f9fe9e.png)

Students of this workshop are expected to use a dongle as well. Reading the Linux instructions it seems that the ID is `1915 521f`.

`/installation.html#linux-only-usb`
![image](https://user-images.githubusercontent.com/130903/88118400-5621fe00-cb72-11ea-9234-79c12eec2452.png)

Here it is in Zadig based on that:

![image](https://user-images.githubusercontent.com/130903/88118217-edd31c80-cb71-11ea-98af-71ad98bcc9e7.png)

It's unclear if this should be done for the Dongle based on the lack of instruction here.

**Comment by japaric** [comment]
(Hello Ana :wave:)

Yes, on Windows the Zadig operation needs to be done *only* for the DK. We should add a note to that extent.

The reason is that we are doing different things on each OS: changing permissions on Linux and changing drivers on Windows.

On Linux, permissions may not let us use the device but the drivers associated to the USB devices by the host work OK with our tools (dk-run, serial-term) and external tools (nrfutil, carge-flash). On Windows, permissions are not an issue but the default drivers do not work with probe-rs based tools like dk-run and cargo-flash (all use the USB bulk interface/driver); they do work with Nordic's nrfutil and `serial-term` (both use the "virtual COM" USB interface/driver). We only use the probe-rs tools with the DK -- the Dongle does not have a probe on board.

**Comment by Hoverbear** [comment]
(Hi! It's been too long! I miss you!)

That makes sense! Thanks for the explanation. I've made a PR for a note. Really loving the material so far. :)
